name: thimar_driver
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.9.3
  animate_do: ^3.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  quick_log: ^5.3.0
  shared_preferences: ^2.2.2
  kiwi: ^4.1.0
  easy_stepper: ^0.6.0
  dotted_border: ^2.1.0
  flutter_html: ^3.0.0-alpha.5
  google_maps_flutter: ^2.5.3
  map_launcher: ^3.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  image_picker: ^1.0.7
  circular_countdown_timer: ^0.2.3
  pin_code_fields: ^8.0.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

